apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: box-collector-pv-claim
  namespace: grafana
spec:
  storageClassName: kube-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ki